development:
  sessions:
    default:
      uri: <%= ENV['MONGOLAB_TYPES_URL'] || 'mongodb://localhost:27017/types_development' %>
    devices:
      uri: <%= ENV['MONGOLAB_DEVICES_URL'] || 'mongodb://localhost:27017/devices_development' %>
    people:
      uri: <%= ENV['MONGOLAB_PEOPLE_URL'] || 'mongodb://localhost:27017/people_development' %>
    jobs:
      uri: <%= ENV['MONGOLAB_JOBS_URL'] || 'mongodb://localhost:27017/jobs_development' %>
  options:
test:
  sessions:
    default:
      database: types_test
      hosts:
        - localhost:27017
      options:
        consistency: :strong
    devices:
      database: devices_test
      hosts:
        - localhost:27017
      options:
        consistency: :strong
    people:
      database: people_test
      hosts:
        - localhost:27017
      options:
        consistency: :strong
    jobs:
      database: jobs_test
      hosts:
        - localhost:27017
      options:
        consistency: :strong
  options:
production:
  sessions:
    default:
      uri: <%= ENV['MONGOLAB_TYPES_URL'] %>
    devices:
      uri: <%= ENV['MONGOLAB_DEVICES_URL'] %>
    people:
      uri: <%= ENV['MONGOLAB_PEOPLE_URL'] %>
    jobs:
      uri: <%= ENV['MONGOLAB_JOBS_URL'] %>
  options:
