pagination:
  page: 1
  per: 25
thumbs:
  sizes: %w(micro, small, medium, big, large)
  micro: 16
  small: 32
  medium: 64
  big: 128
  large: 256
  original: 512
statuses:
  default_order: 1000000
public:
  resources: %w(types categories)
