host: <%= host = "http://www.iana.org/domains/example" %>
another_host: <%= another_host = "http://www.anotherhost.com" %>
validation: 
  valid_uri: 'http://example.com'
  not_valid_uri: 'example'
messages:
  access_denied: 'Access denied'
user: 
  uri: <%= "#{host}/users/alice" %>
  email: 'alice@example.com'
  password: 'example'
another_user: 
  uri: <%= "#{host}/users/bob" %>
  email: 'bob@example.com'
status:
  uri: <%= "#{host}/staus/intensity_set" %>
  name: "Intensity set"
